### ISSUE TITLE
Doesn't support "OpenAPI" (i.e. Swagger v3.0)

### ISSUE THREAD

**Issue by ahri** [Teebytes/TnT-Fuzzer#9]
Is this planned? It looks like a nice tool, but I'm testing out OpenAPI v3.0 at the moment and was disappointed to find that I couldn't use it!

**Comment by xenobyte** [comment]
Hi @ahri,

it is planned, but this is not our highest priority right now.

**Comment by floggle** [comment]
Ah. I guess that's why it's not validating my schema.
Suggestions:
1) DOCUMENT CLEARLY and AT THE TOP on the homepage what OpenAPI versions are supported. I just wasted 30 mins getting this installed (gah, pyjfuzz!).
2) I just wasted another 5 minutes trying to figure out why I was getting a validation error. Given that the api version is included in the spec, it should be VERY easy to do.

**Comment by Thoiz** [comment]
@floggle 
Noted. Just added version checks and error handling with #32 - furthermore, the description was complement

**Comment by Predictor** [comment]
@xenobyte @Thoiz 
I created a PR for OpenAPI 3.0 support.
#51
